server:
  port: 9002
  servlet:
    context-path: '/autenticacao-service/'

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${autenticacaoDBHost}:5432/${autenticacaoDBBase}
    username: ${autenticacaoDBUser}
    password: ${autenticacaoDBPass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: ${eurekaHostname}
    non-secure-port: 9002