server:
  port: 9005
  servlet:
    context-path: '/supermercado-service/'

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${supermercadoDBHost}:5432/${supermercadoDBBase}
    username: ${supermercadoDBUser}
    password: ${supermercadoDBPass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_prefix:
            audit_table_suffix: _auditoria
            revision_field_name: revisao
            revision_type_field_name: tipo
            store_data_at_delete: true
            default_schema: auditoria

sistema:
  nfe-ba-service:
    url: ${NFEBAHost}

eureka:
  instance:
    hostname: ${eurekaHostname}
    non-secure-port: 9005