server:
  port: 9005
  servlet:
    context-path: '/supermercado-service/'

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${supermercadoDBHost}:5432/${supermercadoDBBase}
    username: ${supermercadoDBUser}
    password: ${supermercadoDBPass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

sistema:
  nfe-ba-service:
    tempoProcessamentoNFE: ${tempoProcessamentoNFE}
    url: ${NFEBAHost}

eureka:
  instance:
    hostname: ${eurekaHostname}
    non-secure-port: 9005