server:
  port: 9006
  servlet:
    context-path: '/remedios-service/'

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${remediosDBHost}:5432/${remediosDBBase}
    username: ${remediosDBUser}
    password: ${remediosDBPass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: ${eurekaHostname}
    non-secure-port: 9001