server:
  port: 9007
  servlet:
    context-path: '/gastos-service/'

spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${gastosDBHost}:5432/${gastosDBBase}
    username: ${gastosDBUser}
    password: ${gastosDBPass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: ${eurekaHostname}
    non-secure-port: 9007